name: Repository Management

on:
 push:
  branches:
   - main

 pull_request:
  types:
   - opened

jobs:
 repository-management:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout Repository
     uses: actions/checkout@v2

   - name: Set up Python
     uses: actions/setup-python@v2
     with:
      python-version: '3.8'

   - name: Install Dependencies
     run: pip install -r requirements.txt

   - name: Run Security Checks
     env:
      GITHUB_TOKEN: ${{ secrets.Github_TOKEN }}
     run:
      touch file1.py
    
   - name: Build and Deploy
     run: | 
      # Add Commands
      
